"""
Example: Rust-based AutoDocs with Robyn
Demonstrates deep integration with Robyn's routing system
"""
import sys
sys.path.insert(0, 'robyn_python/python')

from robyn import Robyn, Request
from robyn_extensions import BaseModel, Field, body_v2
from robyn_extensions._robyn_extensions import AutoDocs, RouteMetadata
from typing import Optional, List
import json

# Disable Robyn's built-in OpenAPI before creating the app
import sys
if "--disable-openapi" not in sys.argv:
    sys.argv.append("--disable-openapi")

app = Robyn(__file__)

# Create Rust-based AutoDocs instance
docs = AutoDocs("User Management API", "1.0.0")

# Define Pydantic models
class Address(BaseModel):
    street: str
    city: str
    country: str = "USA"

class UserCreate(BaseModel):
    """User creation model"""
    username: str = Field(min_length=3, max_length=20)
    email: str
    age: int = Field(ge=18, le=120)
    is_active: bool = True
    tags: List[str] = []
    address: Optional[Address] = None

class UserResponse(BaseModel):
    """User response model"""
    id: int
    username: str
    email: str
    age: int
    is_active: bool
    tags: List[str]
    address: Optional[Address]

# Register route: Create user
@app.post("/users")
@body_v2(UserCreate)
def create_user(request: Request, user: UserCreate):
    """Create a new user with validation"""
    # Register this route with AutoDocs
    metadata = RouteMetadata(
        path="/users",
        method="POST",
        summary="Create a new user",
        description="Creates a new user with automatic validation. Username must be 3-20 chars, age 18-120.",
        tags=["users"],
        request_schema=json.dumps(UserCreate.model_json_schema()),
        response_schema=json.dumps(UserResponse.model_json_schema())
    )
    docs.register_route(metadata)

    # Business logic
    user_response = UserResponse(
        id=1,
        username=user.username,
        email=user.email,
        age=user.age,
        is_active=user.is_active,
        tags=user.tags,
        address=user.address
    )
    return user_response.model_dump_json()

# Register route: Get user
@app.get("/users/:id")
def get_user(request: Request):
    """Get a user by ID"""
    # Register this route with AutoDocs
    metadata = RouteMetadata(
        path="/users/{id}",
        method="GET",
        summary="Get user by ID",
        description="Retrieves a single user by their unique ID",
        tags=["users"],
        request_schema=None,
        response_schema=json.dumps(UserResponse.model_json_schema())
    )
    docs.register_route(metadata)

    return UserResponse(
        id=1,
        username="johndoe",
        email="john@example.com",
        age=25,
        is_active=True,
        tags=["python", "rust"],
        address=Address(street="123 Main St", city="NYC")
    ).model_dump_json()

# Register route: List users
@app.get("/users")
def list_users(request: Request):
    """List all users"""
    metadata = RouteMetadata(
        path="/users",
        method="GET",
        summary="List all users",
        description="Returns a list of all users in the system",
        tags=["users"],
        request_schema=None,
        response_schema=json.dumps({
            "type": "array",
            "items": UserResponse.model_json_schema()
        })
    )
    docs.register_route(metadata)

    return json.dumps({
        "users": [
            UserResponse(
                id=1,
                username="johndoe",
                email="john@example.com",
                age=25,
                is_active=True,
                tags=["python"],
                address=None
            ).model_dump()
        ]
    })

# Documentation endpoints (using Rust AutoDocs!)
@app.get("/openapi.json")
def openapi_spec(request: Request):
    """Get OpenAPI specification (generated by Rust!)"""
    return docs.get_openapi_json()

@app.get("/docs")
def swagger_ui(request: Request):
    """Swagger UI documentation (generated by Rust!)"""
    html = docs.get_swagger_ui_html("User Management API")
    return html

@app.get("/redoc")
def redoc_ui(request: Request):
    """ReDoc documentation (generated by Rust!)"""
    html = docs.get_redoc_html("User Management API")
    return html

@app.get("/")
def index(request: Request):
    """API index"""
    return json.dumps({
        "message": "User Management API",
        "version": "1.0.0",
        "docs": {
            "swagger": "http://localhost:8080/docs",
            "redoc": "http://localhost:8080/redoc",
            "openapi": "http://localhost:8080/openapi.json"
        },
        "endpoints": {
            "create_user": "POST /users",
            "get_user": "GET /users/:id",
            "list_users": "GET /users"
        }
    })

if __name__ == "__main__":
    # Disable Robyn's built-in OpenAPI to avoid conflicts
    import os
    os.environ["ROBYN_BROWSER_OPEN"] = "False"

    print("🚀 Starting Robyn with Rust-based AutoDocs...")
    print("📚 Swagger UI: http://localhost:8081/docs")
    print("📚 ReDoc:      http://localhost:8081/redoc")
    print("📄 OpenAPI:    http://localhost:8081/openapi.json")
    print()
    app.start(host="0.0.0.0", port=8081)
